#!/usr/bin/env bash

git add .

echo "============================================>"

if [ "$1" != "" ]; then
    git commit -m "$1"
else
    comment=$(date)
    git commit -m "$comment"
fi

echo "============================================>"

if [ "$2" != "" ]; then
    git push -u origin $2
else
    branch=$(git branch)
    IFS=' ' read -r -a array <<< "$branch"
    git push -u origin ${array[1]}
fi
