<?php $compropagoId = Mage::getSingleton('core/session')->getComproPagoId(); ?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
    <?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<div class="wrapper">
    <?php echo $this->getChildHtml('global_notices') ?>
    <div class="page">
        <?php echo $this->getChildHtml('header') ?>
        <div class="main-container col1-layout">
            <div class="main">
                <?php echo $this->getChildHtml('breadcrumbs') ?>
                <div class="col-main">


                    <?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>
                    <?php if(!empty($compropagoId)){ ?>

                        <div id="receipt" class="receipt">
                            <div class="page-title">
                                <h3>¡Felicitaciones! Su pedido ha sido generado correctamente.</h3>
                            </div>

                            <div id="compropagodContainer" style="width: 100%;">
                                <iframe style="width: 100%; height: 865px;>" id="compropagodFrame"  src="https://www.compropago.com/comprobante/?confirmation_id=<?php echo $compropagoId; ?>"  frameborder="0" scrolling="yes"> </iframe>
                            </div>
                            <?php Mage::getSingleton('core/session')->setComproPagoId(''); ?>

                            <div class="buttons-set">
                                <button type="button" class="button continue-succes" title="<?php echo $this->__('Continue Shopping') ?>" onclick="window.location='<?php echo $this->getUrl() ?>'"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
                            </div>
                        </div>

                        <script type="text/javascript">
                            function resizeIframe() {
                                var container=document.getElementById("compropagodContainer");
                                var iframe=document.getElementById("compropagodFrame");
                                if(iframe && container){
                                    var ratio=585/811;
                                    var width=container.offsetWidth;
                                    var height=(width/ratio);
                                    if(height>937){ height=937;}
                                    iframe.style.width=width + 'px';
                                    iframe.style.height=height + 'px';
                                }
                            }
                            window.onload = function(event) {
                                resizeIframe();
                            };
                            window.onresize = function(event) {
                                resizeIframe();
                            };
                        </script>

                        <?php
                    }else {
                        echo $this->getChildHtml('content');
                    }
                    ?>

                </div>
            </div>
        </div>
        <?php echo $this->getChildHtml('footer') ?>
        <?php echo $this->getChildHtml('before_body_end') ?>
    </div>
</div>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>