<div>
    <ul id="payment_form_<?php echo $this->getMethodCode(); ?>" style="display: none">
       <li>
           <p>
               Realiza tu pago a través de SPEI para cualquier banco, es muy rapido y sencillo.<br>
               Crea la orden y recibiras las instrucciones a tu email para dar de alta la cuenta y realizar la
               transferencia desde tu banca en linea.
           </p>
       </li>
    </ul>
</div>