<?php
/**
 *
 * Form payment cash
 *
 * @author Oswaldo Lopez (waldix86@gmail.com)
 */
?>

<?php  $_code= $this->getMethodCode();
$_model = $this->getMethod();
$_getProviders = $_model->getProviders();
?>
<img id="image_providers" onload="loadImage(this);" src="<?php echo $this->getSkinUrl('images/compropago/providers.png') ?>" class="image_providers_compropago">
<ul id="payment_form_<?php  echo $_code ?>" style="display:none" >
    <label class="label-instructions">Selecciona un establecimiento para realizar el pago en efectivo:</label>
    <?php  if (!$_model->showLogoProviders())
    { ?>
        <li>
            <select id="<?php echo $_code ?>_store"
                    name="payment[store_code]">
                <?php foreach ($_getProviders as $_provider): ?>
                    <option value="<?php echo $_provider['internal_name'] ?>"><?php echo $_provider['name'] ?></option>
                <?php endforeach; ?>
            </select>
        </li>
    <?php } else { ?>
        <li>
            <div class="row stores-compact" style="padding: 5px 15px; opacity: 1; width:100%;" id="<?php echo $_code ?>_store">
                <?php foreach ($_getProviders as $_provider): ?>
                    <!--<php if($_provider['internal_name'] == 'OXXO' || $_provider['internal_name'] == 'SEVEN_ELEVEN' || $_provider['internal_name'] == 'EXTRA' || $_provider['internal_name'] == 'CHEDRAUI'): ?>-->
                    <div class="element-box">
                        <label for="<?php echo $_code ?>_<?php echo $_provider['internal_name'] ?>" class="provider-description <?php echo $_provider['internal_name'] == 'OXXO' ? 'seleccion_store' : '' ?>" onclick="seleccionar(this,'<?php echo $_provider['internal_name'] ?>');">
                            <img src="<?php echo $_provider['image_medium'] ?>" class="image_provider">
                        </label>
                    </div>
                    <!--<php endif; ?>-->
                <?php endforeach; ?>
                <input id="store_code_selected" type="hidden" name="payment[store_code]" value="">
            </div>
        </li>
    <?php } ?>
</ul>
<div>
    <?php echo $this->getMethod()->getConfigData('message');?>
</div>