<?php
/**
 * @author waldix <waldix86@gmail.com>
 */
?>
<div class="page-title">
    <h3>¡Felicitaciones! Su pedido ha sido generado correctamente.</h3>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $expiration_date = Mage::getSingleton('core/session')->getExpirationDate();
      $reference = Mage::getSingleton('core/session')->getReference();
      $step_1 = Mage::getSingleton('core/session')->getStep1();
      $step_2 = Mage::getSingleton('core/session')->getStep2();
      $step_3 = Mage::getSingleton('core/session')->getStep3();
      $bank_number = Mage::getSingleton('core/session')->getBankNumber();
      $bank_name = Mage::getSingleton('core/session')->getBankName();
      $note_extra_comition = Mage::getSingleton('core/session')->getNoteExtraComition();
      $note_expiration_date = Mage::getSingleton('core/session')->getNoteExpirationDate();
      $api_version = Mage::getSingleton('core/session')->getApiVersion();
      //$store_image = Mage::getSingleton('core/session')->getStoreImage();
?>

<?php if ($this->getOrderId()):?>
<?php if ($this->getCanViewOrder()) :?>
    <p><?php echo $this->__('Your order # is: %s.', sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getViewOrderUrl()), $this->escapeHtml($this->getOrderId()))) ?></p>
<?php  else :?>         
    <div class="cp-instruction-section">
      <div class="expiration-date">
        Último día para pagar:
        <span >
        <?php if( $this->__($api_version) === '1.0' ): ?>
          <?php echo date('d-m-Y', strtotime($this->__($expiration_date)))  ?>
        <?php else: ?>
          <?php echo date('d-m-Y', $this->__($expiration_date))  ?>
        <?php endif; ?>
        </span>
      </div>

      <div class="cp-title">Seguir los siguientes pasos:</div>

      <div class="cp-step-box">
        <div class="cp-step">
              <div class="cp-num">1.</div> <span> <?php echo $this->__($step_1) ?> </span>
        </div>
        <div class="cp-step">
            <?php if( $this->__($api_version) === '1.0' || $this->__($api_version) === '1.1' ): ?>
              <div class="cp-num">2.</div>  <?php echo $this->__($step_2) ?>                           
            <?php else: ?>               
              <div class="cp-num">2.</div>  <?php echo $this->__($step_2) ?>
              <div class="account-number-box">
                <div class="account-number">
                  <b><?php echo $this->__($bank_name) ?> - <?php echo $this->__($bank_number) ?></b>
                </div>
                <span class="account-number-note">(El número asignado es único por cada orden) </span>
              </div>              
            <?php endif; ?>
        </div>
        <div class="cp-step">
            <div class="cp-num">3.</div> <?php echo $this->__($step_3) ?>
        </div>
      </div>
      <hr class="cp-grey">
      <span class="cp-note" style="font-size:12px;color: #333;">Oxxo/7Eleven/Extra cobra en caja una comisión de $7.00/$8.00 por concepto de recepción de cobranza.</span>
    </div>

  <div class="cp-warning-box">
        <img src="<?php echo $this->getSkinUrl('images/compropago/warning.png'); ?>" style="margin: -7px 0px 0px 0px;"> 
        <span style="font-size: 12px;"><b>Importante</b></span>
        <ul style="" class="cp-warning">
        <li>El ID de control es: <b><?php echo $this->__($reference) ?></b></li>
        <li>El número de cuenta/tarjeta asignado es único por cada orden de compra.</li>
        <?php if(!empty($note_expiration_date)): ?>
          <li><?php echo $this->__($note_expiration_date) ?></li>
        <?php endif; ?>

        <?php if (!empty($note_extra_comition)): ?>
          <li><?php echo $this->__($note_extra_comition) ?></li>
        <?php endif; ?>

        </ul>
    </div>   
<?php endif;?>
<?php if ($this->getCanViewOrder() && $this->getCanPrintOrder()) :?>
    <p>
        <?php echo $this->__('Click <a href="%s" onclick="this.target=\'_blank\'">here to print</a> a copy of your order confirmation.', $this->getPrintUrl()) ?>
        <?php echo $this->getChildHtml() ?>
    </p>
<?php endif;?>
<?php endif;?>

<?php if ($this->getAgreementRefId()): ?>
    <p><?php echo $this->__('Your billing agreement # is: %s.', sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getAgreementUrl()), $this->escapeHtml($this->getAgreementRefId())))?></p>
<?php endif;?>

<?php if ($profiles = $this->getRecurringProfiles()):?>
<p><?php echo $this->__('Your recurring payment profiles:'); ?></p>
<ul class="disc">
<?php foreach($profiles as $profile):?>
<?php $profileIdHtml = ($this->getCanViewProfiles() ? sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getProfileUrl($profile)), $this->escapeHtml($this->getObjectData($profile, 'reference_id'))) : $this->escapeHtml($this->getObjectData($profile, 'reference_id')));?>
    <li><?php echo $this->__('Payment profile # %s: "%s".', $profileIdHtml, $this->escapeHtml($this->getObjectData($profile, 'schedule_description')))?></li>
<?php endforeach;?>
</ul>
<?php endif;?>

<div class="buttons-set"> 
    <button type="button" class="button" title="<?php echo $this->__('Continue Shopping') ?>" onclick="window.location='<?php echo $this->getUrl() ?>'"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
    <button type="button" class="button" title="Imprimir" onclick="window.print(); return false;"><span><span>Imprimir</span></span></button>
</div>