<?php
/**
 * @author waldix <waldix86@gmail.com>
 */
?>

<?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>
<?php $compropagoId = Mage::getSingleton('core/session')->getCompropagoId(); ?> 

<div id="receipt" class="receipt">
    <div class="page-title">
        <h3 style="font-size: 1.0em;">¡Felicitaciones! Su pedido ha sido generado correctamente.</h3>
    </div>
    <?php if ($this->getOrderId()):?>
        <?php if ($compropagoId == '') :?>
            <p>
                <?php echo $this->__('Your order # is: %s.', sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getViewOrderUrl()), $this->escapeHtml($this->getOrderId()))) ?>
                <?php echo $this->__('Click <a href="%s" onclick="this.target=\'_blank\'">here to print</a> a copy of your order confirmation.', $this->getPrintUrl()) ?>
                <?php echo $this->getChildHtml() ?>
            </p>
        <?php  else :?>
            <div id="compropagodContainer" style="width: 100%;">
                <iframe style="width: 100%; height: 865px;>" id="compropagodFrame"  src="https://www.compropago.com/comprobante/?confirmation_id=<?php echo $compropagoId; ?>"  frameborder="0" scrolling="yes"> </iframe>
            </div>
            <?php Mage::getSingleton('core/session')->setCompropagoId(''); ?>
        <?php endif;?>
        <?php if ($this->getCanViewOrder() && $this->getCanPrintOrder()) :?>
            <p>
                <?php echo $this->__('Click <a href="%s" onclick="this.target=\'_blank\'">here to print</a> a copy of your order confirmation.', $this->getPrintUrl()) ?>
                <?php echo $this->getChildHtml() ?>
            </p>
        <?php endif;?>
    <?php endif;?>

    <?php if ($this->getAgreementRefId()): ?>
        <p><?php echo $this->__('Your billing agreement # is: %s.', sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getAgreementUrl()), $this->escapeHtml($this->getAgreementRefId())))?></p>
    <?php endif;?>

    <?php if ($profiles = $this->getRecurringProfiles()):?>
        <p><?php echo $this->__('Your recurring payment profiles:'); ?></p>
        <ul class="disc">
            <?php foreach($profiles as $profile):?>
                <?php $profileIdHtml = ($this->getCanViewProfiles() ? sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getProfileUrl($profile)), $this->escapeHtml($this->getObjectData($profile, 'reference_id'))) : $this->escapeHtml($this->getObjectData($profile, 'reference_id')));?>
                <li><?php echo $this->__('Payment profile # %s: "%s".', $profileIdHtml, $this->escapeHtml($this->getObjectData($profile, 'schedule_description')))?></li>
            <?php endforeach;?>
        </ul>
    <?php endif;?>
    <div class="buttons-set">
        <button type="button" class="button continue-succes" title="<?php echo $this->__('Continue Shopping') ?>" onclick="window.location='<?php echo $this->getUrl() ?>'"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
    </div>
</div>
<script type="text/javascript">
    function resizeIframe() {
        var container=document.getElementById("compropagodContainer");
        var iframe=document.getElementById("compropagodFrame");
        if(iframe && container){
            var ratio=585/811;
            var width=container.offsetWidth;
            var height=(width/ratio);
            if(height>937){ height=937;}
            iframe.style.width=width + 'px';
            iframe.style.height=height + 'px';
        }
    }

    window.onload = function(event) {
        resizeIframe();
    };
    window.onresize = function(event) {
        resizeIframe();
    };
</script>
